const {
  CONTRACT_P2P,
  CONTRACT_SEEDS,
  CONTRACT_SEEDS_WALLET,
  CONTRACT_SEEDS_VALUES,
  CONTRACT_P2P_SETTINGS
} = process.env

export const Contracts = {
  CONTRACT_SEEDS,
  CONTRACT_P2P,
  CONTRACT_SEEDS_WALLET,
  CONTRACT_SEEDS_VALUES,
  CONTRACT_P2P_SETTINGS
  // token.seeds
}
